import PDFDocument from 'pdfkit';
import { parse } from 'json2csv';
import fs from 'fs';
import path from 'path';

class ReportGeneratorService {
  async generatePDF(reportData, filename) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });
        const filePath = path.join(process.cwd(), 'uploads', `${filename}.pdf`);
        
        // Ensure uploads directory exists
        if (!fs.existsSync(path.join(process.cwd(), 'uploads'))) {
          fs.mkdirSync(path.join(process.cwd(), 'uploads'));
        }

        const stream = fs.createWriteStream(filePath);
        doc.pipe(stream);

        // Header
        doc.fontSize(20).text(`EcoSphere - ${reportData.title}`, { align: 'center' });
        doc.moveDown();
        doc.fontSize(12).text(`Generated by: ${reportData.generatedBy}`);
        doc.text(`Date: ${new Date().toLocaleDateString()}`);
        doc.moveDown();
        doc.text('--------------------------------------------------');
        doc.moveDown();

        // Content
        if (reportData.content && Array.isArray(reportData.content)) {
          reportData.content.forEach(item => {
            doc.fontSize(14).text(item.sectionHeading, { underline: true });
            doc.fontSize(12).text(item.body);
            doc.moveDown();
          });
        } else {
          doc.fontSize(12).text(JSON.stringify(reportData.content, null, 2));
        }

        doc.end();

        stream.on('finish', () => resolve(`/uploads/${filename}.pdf`));
        stream.on('error', (err) => reject(err));
      } catch (error) {
        reject(error);
      }
    });
  }

  generateCSV(reportData) {
    try {
      const fields = Object.keys(reportData.content[0] || {});
      const opts = { fields };
      return parse(reportData.content, opts);
    } catch (error) {
      throw error;
    }
  }
}

export default new ReportGeneratorService();
